### ISSUE TITLE
XBlock: Big Blue Button (3 άτομα) (advanced)

### ISSUE THREAD

**Issue by dnna** [maellak/edx-seminar#1]
Το συγκεκριμένο block θα συνδέεται με ένα big blue button server και θα εμφανίζει 2 επιλογές: "Watch Live" και "Recorded Sessions". Το watch live θα ανοίγει ένα νέο παράθυρο όπως στο screenshot (3) ενώ το Recorded Sessions θα ανακτά και θα εμφανίζει τα βίντεο που έχουν καταγραφεί εως τώρα για το μάθημα, όπως στο screenshot (2).

![1](https://cloud.githubusercontent.com/assets/1296821/6883076/7d9fe900-d5a6-11e4-8302-ef9442ae9e11.png)
(1)

![2015_03_28_23_54_45_recorded_sessions](https://cloud.githubusercontent.com/assets/1296821/6883078/83e67540-d5a6-11e4-9faf-9274f1d62719.png)
(2)

![2015_03_28_23_55_24_bigbluebutton_demo_meeting](https://cloud.githubusercontent.com/assets/1296821/6883082/8a08eb10-d5a6-11e4-9358-8d5dcfa15332.png)
(3)

**Comment by dnna** [comment]
Implemented

**Comment by axilleas** [comment]
:fireworks:

**Comment by wwj718** [comment]
Hi,@dnna  :
Is this xblock opensource?

**Comment by dnna** [comment]
@wwj718 all the xblocks from this seminar are open source, with links on this repo's front page (https://github.com/maellak/edx-seminar) . That said, not all blocks reached a point where they can be used by the public - the ones that did were added to https://github.com/edx/edx-platform/wiki/List-of-XBlocks . For more information you can create an issue on the relevant xblock's repo.

**Comment by wwj718** [comment]
@dnna Thank you for your reply : )
It is seems that the bbbXblock is a project prototype，not like the above pictures
