### ISSUE TITLE
XBlock: SSH client (2 άτομα)

### ISSUE THREAD

**Issue by dnna** [maellak/edx-seminar#7]
Στο συγκεκριμένο block ο καθηγητής θα ορίζει τα στοιχεία ενός server (host, port, username, password) και στον φοιτητή θα εμφανίζεται ένα browser-based SSH client (πχ. http://weavervsworld.com/ssh/ssh.php) το οποίο θα τον συνδέει αυτόματα στο SSH αυτού του server.

Προαιρετικά ο καθηγητής θα μπορεί να προσθέτει στο host και/ή στο username μεταβλητές όπως το username του φοιτητή στο edX, ώστε κάθε φοιτητής να έχει ένα προσωποποιημένο instance.

![webssh22](https://cloud.githubusercontent.com/assets/1296821/6883272/2698cbf6-d5ae-11e4-9460-645ce02d567b.png)

---

Repository: https://github.com/maellak/sshxblock
- https://en.wikipedia.org/wiki/Web-based_SSH
- https://code.google.com/p/shellinabox/
- http://firessh.net/developers.html
- https://github.com/mscdex/ssh2

**Comment by axilleas** [comment]
* https://en.wikipedia.org/wiki/Web-based_SSH
* https://code.google.com/p/shellinabox/
* http://firessh.net/developers.html

**Comment by axilleas** [comment]
https://github.com/maellak/sshxblock

**Comment by dnna** [comment]
Implemented

**Comment by dnna** [comment]
Repo at: https://github.com/Denis1990/sshxblock
