### ISSUE TITLE
XBlock: Slide Viewer (3 άτομα)

### ISSUE THREAD

**Issue by dnna** [maellak/edx-seminar#9]
Στο συγκεκριμένο block ο καθηγητής θα ανεβάζει ένα αρχείο μορφής pptx ή odp. Ο φοιτητής θα βλέπει έναν online slide viewer με τις διαφάνειες που περιέχει το αρχείο.

![2015_03_29_01_14_52_](https://cloud.githubusercontent.com/assets/1296821/6883314/1980c844-d5b1-11e4-9d03-2a5a89fe2ee8.png)

**Comment by dnna** [comment]
Implemented

**Comment by ovnicraft** [comment]
where is implemented ? any xblock ?

**Comment by axilleas** [comment]
@ovnicraft here it is https://github.com/karaariana/slideviewer_new

You can see all the xblocks that were implemented during this seminar at https://github.com/maellak/edx-seminar#contributions

**Comment by ovnicraft** [comment]
@axilleas thanks for info so i am really interested, its ready for production ?

**Comment by axilleas** [comment]
Last time I checked it was in a wotking state. You might want to get in touch with the upstream developers :)

**Comment by ovnicraft** [comment]
Will give a try of course :-)
